#
# ~/.zprofile
#
# This file is run my zsh only for login shells.

# For login shells, import the configured environment generated by
# environment.d(5). This basically applies the same env as what desktop
# applications get, so all terminal-related settings are the there.
#
# shellcheck disable=SC2046

if [[ "$(tty)" = "/dev/tty1" ]]; then
  pgrep Hyprland || startway
fi

if [[ "$(tty)" = "/dev/tty2" ]]; then
  pgrep sway || startway sway
fi
