#!/bin/bash

# File preview handler for lf.
# Arguements passed to previewer script by lf:
#  $1 = preview target file name
#  $2 = width of preview pane
#  $3 = height of preview pane
#  $4 = position x of preview pane
#  $5 = position y of preview pane

set -C -f
IFS="$(printf '%b_' '\n')"; IFS="${IFS%_}"

image() {
   chafa "$1" -f sixel -s "$(($2-2))x$3" | sed 's/#/\n#/g'
}

image_kitty() {
    kitty +icat --silent --transfer-mode file --place "${2}x${3}@${4}x${5}" "$1"
    exit 1
}

case "$1" in
  *.7z|*.a|*.ace|*.alz|*.arc|*.arj|*.bz|*.bz2|*.cab|*.cpio|*.deb|*.gz|*.jar|\
  *.lha|*.lrz|*.lz|*.lzh|*.lzma|*.lzo|*.rar|*.rpm|*.rz|*.t7z|*.tar|*.tbz|\
  *.tbz2|*.tgz|*.tlz|*.txz|*.tZ|*.tzo|*.war|*.xz|*.Z|*.zip)
    als -- "$1"
    exit 0
    ;;
  *.djvu|*.djv)
    djvutxt - <"$1"
    exit 0
    ;;
  *.svg)
    mediainfo "$1"
    exit 0
    ;;
esac

case "$(file --dereference --brief --mime-type -- "$1")" in
  text/troff)
    man -- "$1" | col -b
    ;;
  image/*)
    if [ "$TERM" == "xterm-kitty" ]; then
      image_kitty $1 $2 $3 $4 $5
    else
      image $1 $2 $3 $4 $5
    fi
   ;;
  video/*)
    mediainfo "$1"
    ;;
  application/x-iso9660-image)
    iso-info --no-header -l "$1"
    ;;
	application/pgp-encrypted)
    gpg -d -- "$1"
    ;;
  # application/pdf)
  #   pdftotext -nopgbrk -q -- "$1" -
  #   ;;
	*/pdf)
		CACHE="/tmp/thumb.$(stat --printf '%n\0%i\0%F\0%s\0%W\0%Y' -- "$(readlink -f "$1")" | sha256sum | cut -d' ' -f1)"
		[ ! -f "$CACHE.jpg" ] && pdftoppm -jpeg -f 1 -singlefile "$1" "$CACHE"
    if [ "$TERM" == "xterm-kitty" ]; then
      image_kitty "$CACHE.jpg" $2 $3 $4 $5
    else
      image "$CACHE.jpg" $2 $3 $4 $5
    fi
    ;;
	audio/* | application/octet-stream)
    mediainfo "$1" || exit 1 ;;
  text/* | */xml | application/json | *)
    bat --terminal-width "$4" --color=always --pager=never --style=plain "$1"
    ;;
esac
exit 1
