#!/bin/sh

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
    for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

sxhkd &
xsetroot -cursor_name left_ptr
xrdb -load /home/davide/.config/X11/xresources &
setbg ~/pics/wallpapers
dunst &
picom --experimental-backend &
brightnessctl set 25%
remaps
exec bspwm
