#!/usr/bin/env sh

killall -SIGUSR1 waybar

if [ "$(hyprctl getoption general:gaps_in | awk 'NR==2 {print $2}')" = "0" ]; then
  hyprctl --batch \
    "keyword general:gaps_in 4; \
     keyword general:gaps_out 6; \
     keyword layerrule blur,waybar;"
else
  hyprctl --batch \
    "keyword general:gaps_in 0;\
     keyword general:gaps_out 0;\
     keyword layerrule unset,waybar;\
     keyword layerrule blur,rofi;"
fi
